name: Release

on:
  push:
    tags

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Build
        run: sh build.sh

      - name: Release
        uses: actions/upload-artifact@v3
        with:
          path: build/
